# The URL the site will be built for
base_url = "https://dimuziop.github.io"
title = "DMZ-BLOG"
build_search_index = true
generate_feeds = true
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here
use_cdn = false
theme = "toggle"

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
#    { name = "/tags", url = "/tags", weight = 2 },
#    { name = "/projects", url = "/projects", weight = 3 },
#    { name = "/talks", url= "/talks", weight= 4 },
    { name = "/sobre_mí", url = "/about", weight = 5 },
]

socials = [
    { name = "github", url = "https://github.com/dimuziop/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/dimuziop/", icon = "linkedin" },
    { name = "instagram", url = "https://www.instagram.com/pat.dimuzio/", icon = "instagram" },
]

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "dimuziop"

[extra.analytics.umami]
website_id = "b6249a13-721e-403e-8eb9-81b2895cde07"
